# https://macchinetta.github.io/cloud-guideline/current/ja/AWSCollaboration/CreateAWSApplicationProject.html#id11
cloud:
  aws:
    stack:
      auto: false

spring:
  application.name: was
  
  #データベース接続
  #datasource:
  #  url: jdbc:mysql://localhost:3306/training
  #  username: training
  #  password: training
  datasource:
    url: jdbc:mysql://zein-bn2022-training.ckciplzoe4ah.ap-northeast-1.rds.amazonaws.com:3306/trainingprod
    username: trainingprod
    password: training

  # Internationalization
  messages:
    basename: messages/messages, messages/error-messages, messages/items

  # JSON
  jackson:
      date-format: yyyy/MM/dd'T'HH:mm:ss.SSSZ
      time-zone: Asia/Tokyo

server:
   port : 8080  
   servlet:
      context-path: /

logging:
  level:
    root:  info
    
training:
  security:
    # ユーザー画面
    user:
      # ログインURI
      login-uri: /user/login
      # ログアウトURI
      logout-uri: /user/logout

    # 未認証でアクセス可能URI
    permit-all-uris: 
    
    # 未認証でアクセス可能なRESTコントローラーURI
    permit-all-rest-uris: /common/mail/send,/user/userinfo/password/sent-reset,/user/userinfo/password/reset

    # CORS許可ドメイン
    # Vueのドメインとポート番号を記述
    cors-allowed-origin: "*"
 
 # ---------------------------------------------
 # テスト用設定
 # ---------------------------------------------
#darwin.test:
  # テスト日時 ISO形式　例：2007-12-03T10:15:30
  # system-date-time: 9999-12-03T10:15:30

