cloud:
  aws:
    # https://www.bunkei-programmer.net/entry/2019/01/26/232605
    stack:
      auto: false  
    credentials:
      profileName:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1
  
# for spring-cloud-aws 2.3
# https://docs.awspring.io/spring-cloud-aws/docs/2.3.0/reference/html/index.html#using-amazon-web-services
logging.level.com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error

spring:
  application.name: was
  
  #データベース接続
  datasource:
    url: jdbc:mysql://localhost:3306/training?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: training
  # datasource:
  #  url: jdbc:mysql://zein-bn2022-training.ckciplzoe4ah.ap-northeast-1.rds.amazonaws.com:3306/training
  #  username: training
  #  password: training

  # Internationalization
  messages:
    basename: messages/messages, messages/error-messages, messages/items

  # JSON
  jackson:
      date-format: yyyy/MM/dd'T'HH:mm:ss.SSSZ
      time-zone: Asia/Tokyo

server:
   port : 8080  
   servlet:
      context-path: /

logging:
  level:
    root:  info
    
training:
  security:
    # ユーザー画面
    user:
      # ログインURI
      login-uri: /user/login
      # ログアウトURI
      logout-uri: /user/logout

    # 未認証でアクセス可能URI
    # permit-all-uris: 
    permit-all-uris: "/*,/static/**"

    # 未認証でアクセス可能なRESTコントローラーURI
    permit-all-rest-uris: /common/mail/send,/user/userinfo/password/sent-reset,/user/userinfo/password/reset

    # CORS許可ドメイン
    # Vueのドメインとポート番号を記述
    cors-allowed-origin: "*"

  # ファイルストレージ情報 
  file-storage:
    # 出力先パス（最後に"/"をいれること）
    path-prefix:
      output-stock-result: ./storage/resultStock/
      output-cannot-reserve-order: ./storage/noStockOrder/
    # 基本ファイル名（拡張子まで指定すること） 
    base-filename:
      output-stock-result: stock-result.csv
      output-cannot-reserve-order: cannot-reserve-order.csv
      
 # ---------------------------------------------
 # テスト用設定
 # ---------------------------------------------
#darwin.test:
  # テスト日時 ISO形式　例：2007-12-03T10:15:30
  # system-date-time: 9999-12-03T10:15:30

